# OpenCV functions for manipulating images

- Image I/O operations
- Image Properties 
- Creating new images, accessing pixels and region of interest

### Import libraries

In [8]:
# import libraries
import cv2
import numpy as np
from dataPath import DATA_PATH
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
mpl.rcParams['figure.figsize'] = (6.0, 6.0)
mpl.rcParams['image.cmap'] = 'gray'

### Reading an Image

OpenCV allows reading different types of images (JPG, PNG, etc). You can load grayscale images colour images or you can also load images with Alpha channel (Alpha channel will be discussed in a later section). It uses the imread function which has the following syntax:

Reading function Syntax 

cv2.imread(    filename[, flags]    )

It has 2 arguments:

- Path of the image file: This can be an absolute or relative path. 
- Flags (optional): These flags are used to read an image in a particular format. The default if 1. 

Flag types:

- cv2.IMREAD_GRAYSCALE or 0: Loads image in grayscale mode
- cv2.IMREAD_COLOR or 1: Loads a color image. Any transparency of image will be neglected. It is the default flag.
- cv2.IMREAD_UNCHANGED or -1: Loads image as such including alpha channel.

In [10]:
image_path = DATA_PATH + "/images/number_zero.jpg"

# Read image in Grayscale format, cv2.IMREAD_GRAYSCALE or 0:
sample_mage = cv2.imread(image_path,0)
print(sample_mage)

[[  1   0   3   0   3   0   3   2   4   2   0]
 [  0   1   0   3   3 253 253   0   0   2   1]
 [  0   0   8   0 249 255 255 253  71   1   5]
 [  3   0   2 251 255   2   0 253 254   0   2]
 [  1   5   0 252   4   0   3   0 255   4   0]
 [  0   0   2 255   0   0   0   3 253   0   4]
 [  0   5   4 249   4   2   0   0 255   1   0]
 [  2   0   0 255   3   0   5   0 254   0   4]
 [  0   0   0 255   1   0   0   3 255   0   0]
 [  1   5   0 252   2   2   2  76 250   7   0]
 [  0   0   5   0 254   0   0 255 254   0   1]
 [  0   8   0   3 253 253 255 250   1   2   1]
 [  2   0   0   0   5   0   4   1   3   0   0]]
